# 实验 1:StatefulSet 稳定标识体验(nginx)
apiVersion: v1
kind: Namespace
metadata:
  name: sts-lab
---
# Headless Service:不分配 VIP,DNS 直接解析到每个 Pod
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: sts-lab
spec:
  clusterIP: None            # ← Headless 的标志
  selector:
    app: web-sts
  ports:
    - port: 80
      name: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: sts-lab
spec:
  serviceName: web           # 绑定上面的 Headless Service
  replicas: 3
  selector:
    matchLabels: { app: web-sts }
  template:
    metadata:
      labels: { app: web-sts }
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:      # 每个 Pod 独享一份:www-web-0 / www-web-1 / www-web-2
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
